// <auto-generated />
namespace Coursework.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Renamingofproblemsnames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Renamingofproblemsnames));
        
        string IMigrationMetadata.Id
        {
            get { return "201705271057380_Renaming of problems names"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
