// <auto-generated />
namespace Coursework.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedusernamefieldtouser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedusernamefieldtouser));
        
        string IMigrationMetadata.Id
        {
            get { return "201705201321172_added username field to user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
