// <auto-generated />
namespace Coursework.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addednumberofpartitionforc1andc2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addednumberofpartitionforc1andc2));
        
        string IMigrationMetadata.Id
        {
            get { return "201705292010240_Added number of partition for c1 and c2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
